server:
  port: 8080
  servlet:
    context-path:
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
# mybatis
mybatis-plus:
  mapper-locations: classpath:com/ark/center/dao/*.xml

ark:
  component:
    mq:
      rocketmq:
        producer:
          group: pg_pay
          enabled: false
        server: localhost:9876