server:
  port: 8086
  servlet:
    context-path:
spring:
  application:
    name: pay
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pay?useSSL=false&useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&serverTimezone=UTC&allowPublicKeyRetrieval=True
      username: root
      password: Root1234!@#$
      name: defaultDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-idle: 10
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
  main:
    allow-bean-definition-overriding: true
# mybatis
mybatis-plus:
  mapper-locations: classpath:com/ark/center/dao/*.xml

ark:
  component:
    mq:
      rocketmq:
        producer:
          group: pg_pay
          enabled: true
        server: localhost:9876