server:
  port: 8080
  servlet:
    context-path:
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
# mybatis
mybatis-plus:
  mapper-locations: classpath:com/kt/cloud/dao/*.xml
kt:
  mq:
    rocketmq:
      server: localhost:9876
      producer:
        group: pg_pay
        enabled: true